name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Prepare environment
        run: |
          conda env create -f environment.yml
          conda activate maternity_research

      - name: Run scripts
        # We pass the secrets as environment variables
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          # The environment variables are now available in the shell
          python scripts/narrative_generator.py
